version: '3.8'

services:
  generator:
    build:
      context: ./generator
    environment:
      ASI_API_KEY: ${ASI_API_KEY}
      PYTHONUNBUFFERED: "1"
    ports: 
      - "8000:8000"
    volumes:
      - ./generator/markets:/app/markets
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  resolver:
    build:
      context: ./resolver
    environment:
      ASI_API_KEY: ${ASI_API_KEY}
      GENERATOR_API_URL: "http://generator:8000"
      PYTHONUNBUFFERED: "1"
    ports: 
      - "8001:8001"
    volumes:
      - ./resolver/resolutions:/app/resolutions
    depends_on:
      generator:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: prediction-markets